---
version: 2
project_name: validate-pr-review-app
archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    files:
      - LICENSE
      - README.md
      - third_party_licenses/**/*
builds:
  - binary: bootstrap
    main: cmd/lambda/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
sboms:
  - id: default
    disable: false
