---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: validate-pr-review-app
archives:
  - name_template: "{{.ProjectName}}_lambda_{{.Os}}_{{.Arch}}"
    formats: ["zip"]
    ids:
      - lambda
    files:
      - LICENSE
      - README.md
      - third_party_licenses/**/*
builds:
  - id: lambda
    binary: bootstrap
    main: cmd/lambda/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
sboms:
  - id: default
    disable: false
