---
name: test (workflow_call)
on: workflow_call
permissions: {}
jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@v3.2.2
    with:
      aqua_version: v2.53.9
      go-version: 1.24.5
    permissions:
      pull-requests: write
      contents: read
